services:
  - type: web
    name: open-house-planner
    env: node
    buildCommand: ./build.sh
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: open-house-planner-db
          property: connectionString
      - key: REPLIT_DOMAINS
        sync: false
      - key: REPL_ID
        sync: false
      - key: XAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false

databases:
  - name: open-house-planner-db
    databaseName: openhouseplanner
    user: openhouseplanner
